#include <Wire.h>
#include <Adafruit_MCP4725.h>
#include <SPI.h>
#include <LoRa.h>

// Define I2C DAC instances
Adafruit_MCP4725 dacA;
Adafruit_MCP4725 dacB;

// Hardware Pin Definitions
const int VSS_PIN = 4;             // Isolated Speed Sensor Input (GPIO 4)
const int PEDAL_IN_A = 34;         // Pedal Signal Input A (Analog)
const int PEDAL_IN_B = 35;         // Pedal Signal Input B (Analog)
const int LORA_CS = 5;             // LoRa Chip Select
const int LORA_RST = 14;           // LoRa Reset
const int LORA_DIO0 = 2;           // LoRa Interrupt Pin

// Global Volatile Variables for Interrupt Handling
volatile unsigned long pulseCount = 0;
unsigned long lastUpdateTime = 0;

// System Variables
float currentVehicleSpeed = 0.0;
float targetSpeedLimit = 120.0;    // Starts in Free Zone mode (km/h)
bool insideRestrictedZone = false;
float outputModifier = 1.0;
const float RAMP_UP_RATE = 0.02;   // Safe 2% recovery increment per cycle

// Calibration Constant: Adjust based on your specific vehicle's tires/gearbox
// (Number of speed pulses generated by the car's VSS sensor per 1 kilometer driven)
const float PULSES_PER_KM = 4000.0; 

// Hardware Interrupt Function: Executed instantly every time a pulse hits the optocoupler
void IRAM_ATTR handleVssPulse() {
  pulseCount++;
}

void setup() {
  Serial.begin(115200);
  
  // 1. Initialize Hardware Interrupt for Speed Sensor
  pinMode(VSS_PIN, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(VSS_PIN), handleVssPulse, FALLING);
  
  // 2. Initialize Dual I2C DAC Modules
  dacA.begin(0x60); // Default address
  dacB.begin(0x61); // ADDR pin pulled high
  
  // 3. Initialize SPI LoRa Transceiver
  LoRa.setPins(LORA_CS, LORA_RST, LORA_DIO0);
  if (!LoRa.begin(433E6)) { // Set to 433 MHz or 915 MHz depending on your module version
    Serial.println("Error: LoRa Radio hardware initialization failed!");
    while (1); // Halt system if radio is missing
  }
  Serial.println("System Initialized Successfully. Awaiting RF Zone packets...");
}

void loop() {
  // --- PART 1: TRACK PHYSICAL VEHICLE SPEED ---
  unsigned long currentTime = millis();
  if (currentTime - lastUpdateTime >= 1000) { // Calculate speed once every second
    noInterrupts(); // Temporarily pause interrupts to safely copy volatile data
    unsigned long pulses = pulseCount;
    pulseCount = 0; // Reset counter for next second
    interrupts();   // Resume interrupts
    
    // Convert pulses per second to km/h
    float hoursElapsed = (currentTime - lastUpdateTime) / 3600000.0;
    float distanceKm = pulses / PULSES_PER_KM;
    currentVehicleSpeed = distanceKm / hoursElapsed;
    lastUpdateTime = currentTime;
    
    Serial.print("Current Speed: "); Serial.print(currentVehicleSpeed); Serial.println(" km/h");
  }

  // --- PART 2: CHECK WIRELESS RF ZONE PACKETS ---
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    // Read the incoming speed limit byte sent from the roadside boundary transmitter
    int rxPacketValue = LoRa.read(); 
    
    if (rxPacketValue > 0 && rxPacketValue < 150) { // Validation check
      targetSpeedLimit = (float)rxPacketValue;
      insideRestrictedZone = (targetSpeedLimit < 120.0);
      Serial.print("RF Triggered! New Speed Limit Set To: "); Serial.println(targetSpeedLimit);
    }
  }

  // --- PART 3: READ DRIVER INPUT & APPLY CONTROL LAW ---
  int rawPedalA = analogRead(PEDAL_IN_A);
  int rawPedalB = analogRead(PEDAL_IN_B);

  if (insideRestrictedZone) {
    if (currentVehicleSpeed > targetSpeedLimit) {
      float speedError = currentVehicleSpeed - targetSpeedLimit;
      // Proportional reduction modifier
      outputModifier = 1.0 - (speedError * 0.04); 
      if (outputModifier < 0.15) outputModifier = 0.15; // Safe lower floor limit
    } else {
      outputModifier = 1.0;
    }
  } else {
    // Free Zone: Smoothly ramp throttle back up to prevent forward vehicle lunging
    if (outputModifier < 1.0) {
      outputModifier += RAMP_UP_RATE;
    }
  }

  // --- PART 4: INTERCEPT AND INJECT MODIFIED VOLTAGES ---
  int finalOutputA = rawPedalA * outputModifier;
  int finalOutputB = rawPedalB * outputModifier;

  dacA.setVoltage(finalOutputA, false);
  dacB.setVoltage(finalOutputB, false);

  delay(20); // 50 Hz refresh rate for high automotive control responsiveness
}
